source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import (
                            RegisterView,
                            UserProfileView,
                            UsersProfilesListView,
                            UpdateUserView,
                            UserPasswordChangeView,
                            )

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('profiles/', UsersProfilesListView.as_view(), name='users_profiles_list'),
    path("update/", UpdateUserView.as_view(), name="update_user"),
    path("change_password/", UserPasswordChangeView.as_view(), name="change_password"),
]

source/issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.project_views import (IndexView,
                                        ProjectDetailView,
                                        ProjectCreateView,
                                        ProjectEditView,
                                        ProjectDeleteView,
                                        ChangeProjectUsersView
                                        )
from webapp.views.issue_views import (IssueListView,
                                      IssueDetailView,
                                      IssueCreateView,
                                      IssueEditView,
                                      IssueDeleteView
                                      )
app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_view'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='project_edit'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/change_users/', ChangeProjectUsersView.as_view(), name='chang_project_users'),

    path('issues/list', IssueListView.as_view(), name='issue_list'),
    path('issue/<int:pk>/', IssueDetailView.as_view(), name='issue_view'),
    path('issue/create/', IssueCreateView.as_view(), name='issue_create'),
    path('issue/<int:pk>/edit/', IssueEditView.as_view(), name='issue_edit'),
    path('issue/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue_delete')
]

source/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name="profile",
        verbose_name="Профиль",
        on_delete=models.CASCADE,
    )

    birth_date = models.DateField(
        null=True,
        blank=False,
        verbose_name="Дата рождения",
    )

    avatar = models.ImageField(
        verbose_name="Аватар",
        upload_to="avatars/",
        null=True,
        blank=True
    )

    git_profile = models.URLField(
        null=True,
        blank=True,
        max_length=128,
        verbose_name="Профиль GitHub"
    )

    about_me = models.TextField(
        max_length=2000,
        null=True,
        blank=True,
        verbose_name="О себе")

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        return self.user.username + "'s Profile"

source/accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from accounts.models import Profile

User = get_user_model()


class MyUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get("first_name")
        last_name = cleaned_data.get("last_name")
        if not first_name:
            if not last_name:
                raise ValidationError("Заполните Имя или Фамилию")
        return cleaned_data

    class Meta(UserCreationForm.Meta):
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name')


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("avatar", "birth_date", "git_profile", "about_me")


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()

        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator

# Create your views here.
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from accounts.forms import MyUserCreationForm, UserUpdateForm, ProfileUpdateForm, PasswordChangeForm
from accounts.models import Profile

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = "registration.html"
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


def login_view(request):
    if request.user.is_authenticated:
        return redirect('webapp:index')
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'user_object'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        paginator = Paginator(
            self.get_object().projects.all(),
            self.paginate_related_by,
            self.paginate_related_orphans,
        )

        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)

        kwargs['page_obj'] = page
        kwargs['projects'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()

        return super(UserProfileView, self).get_context_data(**kwargs)


class UsersProfilesListView(PermissionRequiredMixin, ListView):
    model = Profile
    context_object_name = 'profiles'
    template_name = 'profiles_list.html'
    permission_required = 'webapp.change_user_in_own_project'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        return context


class UpdateUserView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    form_profile_class = ProfileUpdateForm
    template_name = "update_profile.html"
    context_object_name = "user_object"

    def get_success_url(self):
        return reverse("accounts:user_profile", kwargs={"pk": self.object.pk})

    def get_object(self, queryset=None):
        return self.request.user

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.get_form()
        profile_form = self.get_profile_form()

        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        profile_form.save()
        return super().form_valid(form)

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileUpdateForm(**form_kwargs)

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_object'

    def form_valid(self, form):
        response = super().form_valid(form)
        update_session_auth_hash(self.request, self.object)
        return response

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse("accounts:user_profile", kwargs={"pk": self.request.user.pk})

source/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Вход{% endblock %}


{% block content %}
    <div class="container">
        <h2>Вход</h2>
    </div>
    <div class="container">
        <form method="post" class="row g-3 text-center ">
            {% include 'partials/form.html' with button_txt="Вход" %}
            <!--{% csrf_token %}
            {% if has_error %}
                <p class="text-danger">Неверное имя пользователя или пароль.</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Имя пользователя:</label>
                <input type="text" name="username" id="username" class="form-control">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Пароль:</label>
                <input type="password" name="password" id="password" class="form-control">
            </div>
            <button class="mt-3 btn btn-primary" type="submit">Войти</button>-->
        </form>
    </div>
{% endblock %}

source/accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Профиль {{ user.pk }}{% endblock title %}

{% block nav %}
    {% if user_object == user %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:update_user' %}">Обновить профиль</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:change_password' %}">Изменить пароль</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Профиль пользователя {{ user_object.username }}</h2>
    </div>
    <div class="container col-xxl-8 px-4 py-5">
        <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
            <div class="col-lg-6">
                <h5 class="display-5 fw-bold lh-1 mb-3">@{{ user_object.username }}</h5>
                <p><strong>Имя:</strong> {{ user_object.first_name|default:"Не указанo" }}</p>
                <p><strong>Фамилия:</strong> {{ user_object.last_name|default:"Не указана" }}</p>
                <p><strong>Дата рождения:</strong> {{ user_object.profile.birth_date|date:'d.m.Y'|default:"Не указана" }}</p>
                <p><strong>Почта:</strong> {{ user_object.email|default:"Не указана"}}</p>
                <p class="lead">О себе: {{ product.description }}</p>
                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                    <strong>Профиль GitHub:</strong> {{ user_object.git_profile|default:"Не указан"}}
                </div>
            </div>
            <div class="col-lg-6">
                {% if user_object.profile.avatar %}
                    <img src="{{ user_object.profile.avatar.url }}" alt="user avatar">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container">
        <h3><strong>Участие в проектах:</strong></h3>
        {% include "partials/projects_list.html" %}
    </div>
{% endblock content %}

source/accounts/templates/profiles_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список пользователей{% endblock title %}

{% block content %}

    <div class="container">
        <div class="my-3 p-3 bg-body rounded shadow-sm">
            <h4 class="border-bottom pb-2 mb-0">Список всех пользователей</h4>

            {% for profile in profiles %}
            <div class="d-flex text-muted pt-3">
                <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                    <div class="d-flex justify-content-between">
                        <strong class="text-gray-dark">
                            <a href="{% url 'accounts:user_profile' pk=profile.user.pk %}">
                                {{ profile.user.first_name|default:"Не указанo" }}
                                {{ profile.user.last_name|default:"Не указанo" }}
                            </a>
                        </strong>
                    </div>
                    <span class="d-block">@{{ profile.user.username }}</span>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}

source/accounts/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Регистрация{% endblock %}

{% block nav %}{% endblock %}
{% block content %}

    <div class="container">
        <h2>Регистрация</h2>
    </div>

    <div class="container">
        <form class="row g-3" method="post">
            {% include 'partials/form.html' with button_txt="Зарегистрироваться" %}
        </form>
    </div>

{% endblock %}

source/accounts/templates/update_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Профиль {{ user.pk }}{% endblock title %}

{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:user_profile" user.pk %}">Назад</a>
    </li>
{% endblock nav %}

{% block content %}
    <div class="container">
        <h2>Обновление профиля</h2>
    </div>
    <div class="container">
        <form method="post" enctype="multipart/form-data" class="row g-3">
            {% csrf_token %}
            {% include "partials/form.html" with fields_only=True %}
            {% include "partials/form.html" with fields_only=True form=profile_form %}
            <input type="submit" value="Обновить">
        </form>
    </div>

{% endblock content %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Смена пароля{% endblock title %}

{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:user_profile" user.pk %}">Назад</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "accounts:update_user" %}">Обновить профиль</a>
    </li>
{% endblock nav %}

{% block content %}
    <div class="container">
        <h2>Смена пароля</h2>
    </div>
    <div class="container">
        <form method="POST" class="row g-3">
            {% include 'partials/form.html' with button_txt='Изменить' %}
        </form>
    </div>

{% endblock content %}