source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import (
                            RegisterView,
                            UserProfileView,
                            UsersProfilesListView,
                            UpdateUserView,
                            UserPasswordChangeView,
                            )

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path('profiles/', UsersProfilesListView.as_view(), name='users_profiles_list'),
    path("update/", UpdateUserView.as_view(), name="update_user"),
    path("change_password/", UserPasswordChangeView.as_view(), name="change_password"),
]

source/issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.project_views import (IndexView,
                                        ProjectDetailView,
                                        ProjectCreateView,
                                        ProjectEditView,
                                        ProjectDeleteView,
                                        ChangeProjectUsersView
                                        )
from webapp.views.issue_views import (IssueListView,
                                      IssueDetailView,
                                      IssueCreateView,
                                      IssueEditView,
                                      IssueDeleteView
                                      )
app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_view'),
    path('project/create/', ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='project_edit'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('project/<int:pk>/change_users/', ChangeProjectUsersView.as_view(), name='chang_project_users'),

    path('issues/list', IssueListView.as_view(), name='issue_list'),
    path('issue/<int:pk>/', IssueDetailView.as_view(), name='issue_view'),
    path('issue/create/', IssueCreateView.as_view(), name='issue_create'),
    path('issue/<int:pk>/edit/', IssueEditView.as_view(), name='issue_edit'),
    path('issue/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue_delete')
]

source/webapp/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class IssueModel(models.Model):
    summary = models.CharField(max_length=200, null=False, blank=False, verbose_name="Заголовок",
                               validators=(MinLengthValidator(10),))
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Описание")
    status = models.ForeignKey('webapp.StatusModel', on_delete=models.PROTECT,
                               related_name='status', verbose_name="Статус")
    type = models.ManyToManyField('webapp.TypeModel', related_name='type', blank=True, verbose_name="Тип")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    project = models.ForeignKey('webapp.ProjectModel',
                                on_delete=models.CASCADE,
                                related_name='issues',
                                verbose_name="Проект",
                                null=True,
                                default=1)

    def __str__(self):
        return f"{self.pk}. {self.summary}, {self.type}, {self.status}."

    class Meta:
        db_table = 'issues'
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        permissions = (
            ("add_issue_in_own_project", "Добавлять задачи в свой проект"),
            ("change_issue_in_own_project", "Изменять задачи в своем проекте"),
            ("delete_issue_in_own_project", "Удалять задачи в своем проекте"),
        )


class StatusModel(models.Model):
    title = models.CharField(max_length=32, null=False, blank=False)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = 'statuses'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class TypeModel(models.Model):
    title = models.CharField(max_length=32, null=False, blank=False)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = 'types'
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class ProjectModel(models.Model):
    title = models.CharField(max_length=50, blank=False, verbose_name="Название")
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Описание")
    started = models.DateField(null=False, blank=False, verbose_name="Дата начала")
    finished = models.DateField(null=True, blank=True, verbose_name="Дата окончания")
    users = models.ManyToManyField(User, related_name='projects', verbose_name="Пользователи проекта")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        db_table = 'projects'
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'
        permissions = (
            ("change_user_in_own_project", "Изменять список пользователей в своем проекте"),
        )

source/webapp/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils.http import urlencode
from django.views import View
from django.views.generic import TemplateView, FormView, ListView

# Create your views here.
from webapp.base import FormView as CustomFormView
from webapp.forms import IssueForm, SearchForm
from webapp.models import IssueModel


# class IndexView(View):
#     def get(self, request, *args, **kwargs):
#         issues = IssueModel.objects.order_by('-updated_at')
#         return render(request, 'index.html', {'issues': issues})

class IndexView(ListView):
    model = IssueModel
    context_object_name = 'issues'
    template_name = 'index.html'
    paginate_by = 10
    paginate_orphans = 0

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
            print(queryset)
        return queryset.order_by('-updated_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm()
        if self.search_value:
            context['form'] = SearchForm(initial={'search': self.search_value})
            context['search'] = self.search_value
        return context

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')


class IssueCreate(CustomFormView):
    form_class = IssueForm
    template_name = 'issue_create.html'

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_redirect_url(self):
        return redirect('issue_view', pk=self.object.pk)


class IssueView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        issue = get_object_or_404(IssueModel, pk=kwargs.get("pk"))
        context['issue'] = issue
        return context


class IssueEdit(FormView):
    form_class = IssueForm
    template_name = 'issue_edit.html'

    def dispatch(self, request, *args, **kwargs):
        self.issue = self.get_object()
        return super(IssueEdit, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['issue'] = self.issue
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.issue
        return kwargs

    def form_valid(self, form):
        self.issue = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('issue_view', kwargs={"pk": self.issue.pk})

    def get_object(self):
        return get_object_or_404(IssueModel, pk=self.kwargs.get("pk"))


class IssueDelete(TemplateView):
    def get(self, request, pk=None, *args, **kwargs):
        issue = get_object_or_404(IssueModel, pk=pk)
        return render(request, 'issue_delete.html', {'issue': issue})

    def post(self, request, pk=None, *args, **kwargs):
        issue = get_object_or_404(IssueModel, pk=pk)
        issue.delete()
        return redirect('index')

source/webapp/views/base_views.py
from django.shortcuts import redirect, render
from django.views import View


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ""
    object = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        return self.get_redirect_url()

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return redirect(self.redirect_url)

    def get_context_data(self, **kwargs):
        return kwargs

source/webapp/views/issue_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, DetailView

# Create your views here.
from webapp.views.base_views import FormView as CustomFormView
from webapp.forms import IssueForm, SearchForm
from webapp.models import IssueModel, ProjectModel


class IssueListView(ListView):
    model = IssueModel
    context_object_name = 'issues'
    template_name = 'issue/issue_list.html'
    paginate_by = 10
    paginate_orphans = 0

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
            print(queryset)
        return queryset.order_by('-updated_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm()
        if self.search_value:
            context['form'] = SearchForm(initial={'search': self.search_value})
            context['search'] = self.search_value
        return context

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')


class IssueCreateView(PermissionRequiredMixin, CustomFormView):
    form_class = IssueForm
    template_name = 'issue/issue_create.html'
    permission_required = 'webapp.add_issue_in_own_project'

    def get_project(self):
        project_pk = self.request.POST.get("project")
        return get_object_or_404(ProjectModel, pk=project_pk)

    def has_permission(self):
        has_permission = super().has_permission()

        if self.request.method == "POST":
            has_permission = (
                    has_permission
                    and self.get_project().users.filter(pk=self.request.user.pk).exists()
            )
        return has_permission

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_redirect_url(self):
        return redirect('webapp:issue_view', pk=self.object.pk)


class IssueDetailView(DetailView):
    template_name = 'issue/issue_view.html'
    model = IssueModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(context)
        return context


class IssueEditView(PermissionRequiredMixin, UpdateView):
    form_class = IssueForm
    template_name = 'issue/issue_edit.html'
    model = IssueModel
    permission_required = 'webapp.change_issue_in_own_project'

    def get_success_url(self):
        return reverse('webapp:issue_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return (
            super().has_permission()
            and self.get_object().project.users.filter(pk=self.request.user.pk).exists()
        )


class IssueDeleteView(PermissionRequiredMixin, DeleteView):
    model = IssueModel
    template_name = 'issue/issue_delete.html'
    success_url = reverse_lazy('webapp:issue_list')
    permission_required = 'webapp.delete_issue_in_own_project'

    def has_permission(self):
        return (
                super().has_permission()
                and self.get_object().project.users.filter(pk=self.request.user.pk).exists()
        )

source/webapp/views/project_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import ProjectModel
from webapp.forms import ProjectForm, ProjectUsersForm


class IndexView(ListView):
    model = ProjectModel
    context_object_name = 'projects'
    template_name = 'project/index.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.order_by("-started")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        return context


class ProjectDetailView(DetailView):
    template_name = 'project/project_view.html'
    model = ProjectModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        issues = self.object.issues.order_by('-created_at')
        context['issues'] = issues
        return context


class ProjectCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'webapp.add_projectmodel'
    model = ProjectModel
    form_class = ProjectForm
    template_name = 'project/project_create.html'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        response = super(ProjectCreateView, self).form_valid(form)
        self.object.users.add(self.request.user)
        return response


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    form_class = ProjectForm
    template_name = 'project/project_edit.html'
    model = ProjectModel
    permission_required = 'webapp.change_projectmodel'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    model = ProjectModel
    template_name = 'project/project_delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_projectmodel'


class ChangeProjectUsersView(PermissionRequiredMixin, UpdateView):
    model = ProjectModel
    template_name = 'project/change_users.html'
    form_class = ProjectUsersForm
    permission_required = 'webapp.change_user_in_own_project'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return (
                super().has_permission()
                and self.get_object().users.filter(pk=self.request.user.pk).exists()
        )

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Local styles-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container">
            <a class="navbar-brand" href={% url 'webapp:index' %}>Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    {% if not user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:registration' %}?next={{ request.get_full_path }}">Регистрация</a>
                        </li>
                    {% else %}
                        {% block nav %}{% endblock %}
                        {% if perms.webapp.add_projectmodel %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'webapp:project_create' %}">Создать проект</a>
                            </li>
                        {% endif %}
                        {% if perms.webapp.change_user_in_own_project %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:users_profiles_list' %}">Список профилей</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'webapp:issue_list' %}">Список задач</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:user_profile' user.id %}">Профиль {{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выход</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page content-->
    {% block content %}

    {% endblock %}
    <!--Footer-->
    <footer>
        <hr>
        <div class="container">
            <p>&copy; MdR 2021</p>
        </div>
    </footer>

    <!-- Bootstrap scripts-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Главная{% endblock %}

{% block nav %}
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'issue_create' %}">Создать задачу</a>
    </li>
{% endblock %}

{% block content %}
    <div class="container">

    </div>
    <div class="container">
        <h2>Трекер задач</h2>
        {% include 'partials/simple_search.html' %}
    </div>

    <div class="container">
        <div class="row">
            {% for issue in issues %}
                <div class="col-md-10">
                    <div class="card">
                        <div class="card-body">
                            <a href="{% url 'issue_view' issue.pk %}" style="text-decoration: none"><h5 class="card-title">{{ issue.summary }}</h5></a>

                                {% for type in issue.type.all %}
                                    {% if type.title == 'Bug' %}
                                        <span class="badge rounded-pill bg-danger">
                                            {{ type.title }}
                                        </span>
                                    {% elif type.title == 'Task' %}
                                        <span class="badge rounded-pill bg-primary">
                                            {{ type.title }}
                                        </span>
                                    {% else %}
                                        <span class="badge rounded-pill bg-warning text-dark">
                                            {{ type.title }}<!--{% if not forloop.last %}, {% else %}. {% endif %}-->
                                        </span>
                                    {% endif %}
                                {% endfor %}

                            <p class="card-text">{{ issue.description|truncatechars:100 }}</p>
                            <a href="{% url 'issue_edit' issue.pk %}" class="btn btn-outline-info btn-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg> Редактировать
                            </a>
                            <a href="{% url 'issue_delete' issue.pk %}" class="btn btn-outline-danger btn-sm">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg> Удалить
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}

            {% if is_paginated %}
                {% include 'partials/pagination.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}